/*
========= DESENVOLVEDORES =========

ANA PAULA BESSA MEDEIROS
MATEUS XIMENES DE OLIVEIRA
MATHEUS FERRAZ CAPUCHO
PEDRO HENRIQUE BRIGAGÃO DE AVILA
RENATO MASTEGUIM NETO

*/
#include <iostream>
#include <string>
#include <ctime>
#include "Fate.h"
#include "Texto.h"
using namespace std;

void badending();

void introducao() {
    cout << "\n\n======================== FATE RPG ========================\n\n";
    loading(3000);
    cout << "29 de novembro de 2017 - Fuyuki, Japao\n\n";
    loading(2500);
    cout << "O clima ameno do outono ja vai se transformando no frio de inverno, porem os ventos sao mais agradaveis que os da Inglaterra, de uma forma acolhedora.\n";
    loading(4500);
    cout << "Desde que chegou ao Japao, sente-se como se todos os seus passos estivessem sendo observados; se bem que pela situacao, muito provavelmente eles realmente estejam.\n";
    loading(4500);
    cout << "Voce vai caminhando tranquilamente ate o local combinado, uma igreja isolada, na periferia de Fuyuki.\n";
    loading(3500);
    cout << "Ao chegar, antes mesmo de abrir a porta, ela ja se abre, como se sentisse a sua presenca.\n\n";
    loading(3000);
    cout << "  -Vejo que realmente e um homem pontual, nao esperava menos de um nobre mago britanico.\n\n";
    loading(3500);
    cout << "Disse um homem alto, de aspecto jovem, entre 30 e 35 anos, utilizando uma batina negra catolica.\n\n";
    loading(3500);
    cout << "  -Apenas por formalidade, meu nome e Kirei Kotomine, serei o mediador dessa guerra pelo Santo Graal, selecionado pela Igreja.\n\n";
    loading(3500);
    cout << "  -Prazer, meu nome e: ";
    loading(3000);
}

void escolha_saber(string nome) {
    cout << "\n  -Se deseja lutar ao lado do servo da classe Saber, " << nome << ", sei que ele tambem aceitara lutar ao seu lado.\n\n";
    loading(4500);
    cout << "  -Todos os preparativos para o ritual de invocacao estao prontos, vamos, apresse-se, pois seus inimigos nao irao te esperar!\n\n";
    loading(4500);
    cout << "Nisso, voce repara que toda a igreja ja estava preparada para o ritual, como se ate mesmo Kirei soubesse a classe escolhida antes de ti.\n";
    loading(4500);
    cout << "Porem, seu orgulho faz com que pense que isso eh apenas uma coincidencia.\n\n";
    loading(3000);
    cout << "  -Nao se assuste com a simplicidade, o ritual eh muito simples, pois quem faz a real invocacao eh o proprio Graal.\n\n";
    loading(4500);
    cout << "Realmente, o unico preparativo era um grande circulo cerimonial aos pes do altar com um objeto ao meio,\n";
    loading(4500);
    cout << "Porem, pela escuridao da noite, nao dava para perceber o que ele era.\n\n";
    loading(3000);
    cout << "  -Pois bem, eu " << nome << ", clamo que junte-se a mim a essa batalha.\n";
    loading(3000);
    cout << "  -Vamos vencer nossos inimigos e tomar aquilo que e nosso.\n";
    loading(3000);
    cout << "  -Nao por uma familia, por um grande bem ou por uma ordem.\n";
    loading(3000);
    cout << "  -Mas sim por nos mesmos, pelo nosso orgulho, pelo objetivo que guardamos em nossos coracoes.\n";
    loading(3500);
    cout << "  -Venha a mim e juntos vamos vencer essa guerra, SABER!\n\n";
    loading(3000);
    cout << "Na mesma hora, um grande brilho faz voce fechar seus olhos por alguns instantes.\n";
    loading(3000);
    cout << "Quando abre seus olhos novamente, envolto a uma leve neblina, que antes nao estava la, esta um homem, quase um menino.\n";
    loading(4500);
    cout << "Voce nao diria que ele possui mais do que 30 anos, mas mesmo assim, possuia a maior presenca de que ja havia visto.\n\n";
    loading(4500);
    cout << "  -Compartilho de seus desejos e louvo sua determinacao, lutarei ao seu lado com tudo que puder, mestre.\n";
    loading(4500);
    cout << "  -Me chamo Arthur, Arthur Pendragon, eu e minha espada lutaremos por voce em suas batalhas\n\n.";
    loading(3500);
    cout << "  -Meu nome e " << nome << " e serei digno da confianca depositada.\n\n";
    loading(3000);
    cout << "Agora a sala estava mais clara, pois as nuvens no ceu sairam de frente da lua.\n";
    loading(3000);
    cout << "Gracas a isso, conseguiu perceber melhor como seu servo era.\n";
    loading(3000);
    cout << "Ele vestia uma armadura prateada de corpo inteiro, com detalhes em dourado e tecidos azuis.\n";
    loading(3500);
    cout << "Possuia cabelos loiros e curtos, com olhos azuis gentis mas ao mesmo tempo intimidadores.\n";
    loading(3500);
    cout << "Em sua mao estava uma grande espada de cores semelhantes a dos detalhes de sua armadura, sendo que o dourado da arma parecia brilhar como a lua.\n\n";
    loading(4500);
    cout << "  -Incrivel, realmente incrivel, quase invejavel! _ Disse Kirei aplaudindo lentamente\n";
    loading(3500);
    cout << "  -Porem, como ja avisei, seus inimigos nao irao esperar ate que toda a apresentacao acabe se continuar assim.\n";
    loading(4500);
    cout << "  -Aproveitem o final desta noite, afinal, nunca se sabe, essa ainda pode ser sua ultima noite\n\n";
    loading(3500);
    cout << "Mesmo em toda a situacao de guerra em que se encontra, a leve risada que Kirei deu ao final de sua frase ainda foi a coisa mais bizarra da noite\n";
    loading(4500);
    cout << "Apos uma leve despedida, voce e Arthur saem da igreja em direcao ao centro de Fuyuki, onde estava hospedado.\n\n";
    loading(4500);
}

void escolha_archer(string nome) {
    cout << "\n  -Se deseja lutar ao lado do servo da classe Archer, " << nome << ", sei que ele tambem aceitara lutar ao seu lado.\n\n";
    loading(4500);
    cout << "  -Todos os preparativos para o ritual de invocacao estao prontos, vamos, apresse-se, pois seus inimigos nao irao te esperar!\n\n";
    loading(4500);
    cout << "Nisso, voce repara que toda a igreja ja estava preparada para o ritual, como se ate mesmo Kirei soubesse a classe escolhida antes de ti.\n";
    loading(4500);
    cout << "Porem, seu orgulho faz com que pense que isso eh apenas uma coincidencia.\n\n";
    loading(3500);
    cout << "  -Nao se assuste com a simplicidade, o ritual eh muito simples, pois quem faz a real invocacao eh o proprio Graal.\n\n";
    loading(4500);
    cout << "Realmente, o unico preparativo era um grande circulo cerimonial aos pes do altar com um objeto ao meio,\n";
    loading(3000);
    cout << "Porem, pela escuridao da noite, nao dava para perceber o que ele era.\n\n";
    loading(3000);
    cout << "  -Pois bem, eu " << nome << ", clamo que junte-se a mim a essa batalha.\n";
    loading(3000);
    cout << "  -Vamos vencer nossos inimigos e tomar aquilo que e nosso.\n";
    loading(3000);
    cout << "  -Nao por uma familia, por um grande bem ou por uma ordem.\n";
    loading(3000);
    cout << "  -Mas sim por nos mesmos, pelo nosso orgulho, pelo objetivo que guardamos em nossos coracoes.\n";
    loading(3500);
    cout << "  -Venha a mim e juntos vamos vencer essa guerra, ARCHER!\n\n";
    loading(3000);
    cout << "Na mesma hora, um grande brilho faz voce fechar seus olhos por alguns instantes.\n";
    loading(3000);
    cout << "Quando abre seus olhos novamente, envolto a uma leve neblina, que antes nao estava la, esta um homem alto.\n";
    loading(4500);
    cout << "Possuia uma presenca unica que irradiou toda a igreja e, ao seu lado direito, possuia um canhao quase de seu tamanho\n\n";
    loading(4500);
    cout << "  -Compartilho de seus desejos e louvo sua determinacao, lutarei ao seu lado com tudo que puder, mestre.\n";
    loading(4500);
    cout << "  -Me chamo Napoleao Bonaparte, e juntos vamos vencer, conquistar nossos inimigos!\n";
    loading(3500);
    cout << "  -Meu nome e " << nome << " e serei digno da confianca depositada.\n\n";
    loading(3000);
    cout << "Agora a sala estava mais clara, pois as nuvens no ceu sairam de frente da lua.\n";
    loading(3000);
    cout << "Gracas a isso, conseguiu perceber melhor como seu servo era.\n";
    loading(3000);
    cout << "Ele vestia roupas brancas e vermelhas, com uma longa bora preta e uma longa faixa vermelha.\n";
    loading(3500);
    cout << "Possuia cabelos ruivos e curto, olhos azuis escuros e um sorriso fixo em seu rosto\n";
    loading(3000);
    cout << "O canhao ao seu lado parecia ainda maior agora, mesmo para um servo, deve ser muito dificil manusea-lo\n\n";
    loading(4500);
    cout << "  -Incrivel, realmente incrivel, quase invejavel! _ Disse Kirei aplaudindo lentamente\n";
    loading(3000);
    cout << "  -Porem, como ja avisei, seus inimigos nao irao esperar ate que toda a apresentacao acabe se continuar assim.\n";
    loading(4500);
    cout << "  -Aproveitem o final desta noite, afinal, nunca se sabe, essa  pode ser sua ultima...\n\n";
    loading(3500);
    cout << "Mesmo em toda a situacao de guerra em que se encontra, a leve risada que Kirei deu ao final de sua frase ainda foi a coisa mais bizarra da noite\n";
    loading(4500);
    cout << "Apos uma leve despedida, voce e Napoleao saem da igreja em direcao ao centro de Fuyuki, onde estava hospedado.\n\n";
    loading(4500);
}

void escolha_lancer(string nome) {
    cout << "\n  -Se deseja lutar ao lado do servo da classe Lancer, " << nome << ", sei que ele tambem aceitara lutar ao seu lado.\n\n";
    loading(4500);
    cout << "  -Todos os preparativos para o ritual de invocacao estao prontos, vamos, apresse-se, pois seus inimigos nao irao te esperar!\n\n";
    loading(4500);
    cout << "Nisso, voce repara que toda a igreja ja estava preparada para o ritual, como se ate mesmo Kirei soubesse a classe escolhida antes de ti.\n";
    loading(4500);
    cout << "Porem, seu orgulho faz com que pense que isso eh apenas uma coincidencia.\n\n";
    loading(3500);
    cout << "  -Nao se assuste com a simplicidade, o ritual eh muito simples, pois quem faz a real invocacao eh o proprio Graal.\n\n";
    loading(4500);
    cout << "Realmente, o unico preparativo era um grande circulo cerimonial aos pes do altar com um objeto ao meio,\n";
    loading(4500);
    cout << "Porem, pela escuridao da noite, nao dava para perceber o que ele era.\n\n";
    loading(3000);
    cout << "  -Pois bem, eu " << nome << ", clamo que junte-se a mim a essa batalha.\n";
    loading(3000);
    cout << "  -Vamos vencer nossos inimigos e tomar aquilo que e nosso.\n";
    loading(3000);
    cout << "  -Nao por uma familia, por um grande bem ou por uma ordem.\n";
    loading(3000);
    cout << "  -Mas sim por nos mesmos, pelo nosso orgulho, pelo objetivo que guardamos em nossos coracoes.\n";
    loading(3500);
    cout << "  -Venha a mim e juntos vamos vencer essa guerra, LANCER!\n\n";
    loading(3000);
    cout << "Na mesma hora, um grande brilho faz voce fechar seus olhos por alguns instantes.\n";
    loading(3500);
    cout << "Quando abre seus olhos novamente, envolto a uma leve neblina, que antes nao estava la, esta um homem mais jovem que voce.\n";
    loading(4500);
    cout << "Junto com sua aparencia jovem, possuia uma feicao despreocupada mas ao mesmo tempo muito confiante.\n\n";
    loading(4500);
    cout << "  -Suas palavras me motivam. Agora, minha vida e minha lanca pertencem a voce.\n";
    loading(3000);
    cout << "  -Me chamo Cu Chulainn, e juntos batalharemos ate o ultimo suspiro de nossas vidas.\n\n";
    loading(3500);
    cout << "  -Meu nome e " << nome << " e serei digno da confianca depositada.\n\n";
    loading(3000);
    cout << "Agora a sala estava mais clara, pois as nuvens no ceu sairam de frente da lua.\n";
    loading(3500);
    cout << "Gracas a isso, conseguiu perceber melhor como seu servo era.\n";
    loading(3000);
    cout << "Ele vestia uma roupa de tecido azul e preto, com apenas algumas partes de uma armadura prateada.\n";
    loading(3500);
    cout << "Possuia cabelos longos e azuis, presos a um rabo de cavalo, e olhos vermelhos imponentes.\n";
    loading(3500);
    cout << "Em sua mao estava uma grande lanca verde, mas que emanava uma aura vermelha que era perceptivel ao movimento.\n\n";
    loading(4500);
    cout << "  -Incrivel, realmente incrivel, quase invejavel! _ Disse Kirei aplaudindo lentamente\n";
    loading(3500);
    cout << "  -Porem, como ja avisei, seus inimigos nao irao esperar ate que toda a apresentacao acabe se continuar assim.\n";
    loading(4500);
    cout << "  -Aproveitem o final desta noite, afinal, nunca se sabe, essa  pode ser sua ultima...\n\n";
    loading(3500);
    cout << "Mesmo em toda a situacao de guerra em que se encontra, a leve risada que Kirei deu ao final de sua frase ainda foi a coisa mais bizarra da noite\n";
    loading(4500);
    cout << "Apos uma leve despedida, voce e Cu Chulainn saem da igreja em direcao ao centro de Fuyuki, onde estava hospedado.\n\n";
    loading(4500);
}

void escolha_caster(string nome) {
    cout << "\n  -Se deseja lutar ao lado do servo da classe Caster, " << nome << ", sei que ele tambem aceitara lutar ao seu lado.\n\n";
    loading(4500);
    cout << "  -Todos os preparativos para o ritual de invocacao estao prontos, vamos, apresse-se, pois seus inimigos nao irao te esperar!\n\n";
    loading(4500);
    cout << "Nisso, voce repara que toda a igreja ja estava preparada para o ritual, como se ate mesmo Kirei soubesse a classe escolhida antes de ti.\n";
    loading(4500);
    cout << "Porem, seu orgulho faz com que pense que isso eh apenas uma coincidencia.\n\n";
    loading(3500);
    cout << "  -Nao se assuste com a simplicidade, o ritual eh muito simples, pois quem faz a real invocacao eh o proprio Graal.\n\n";
    loading(4500);
    cout << "Realmente, o unico preparativo era um grande circulo cerimonial aos pes do altar com um objeto ao meio,\n";
    loading(4500);
    cout << "Porem, pela escuridao da noite, nao dava para perceber o que ele era.\n\n";
    loading(3000);
    cout << "  -Pois bem, eu " << nome << ", clamo que junte-se a mim a essa batalha.\n";
    loading(3000);
    cout << "  -Vamos vencer nossos inimigos e tomar aquilo que e nosso.\n";
    loading(3000);
    cout << "  -Nao por uma familia, por um grande bem ou por uma ordem.\n";
    loading(3000);
    cout << "  -Mas sim por nos mesmos, pelo nosso orgulho, pelo objetivo que guardamos em nossos coracoes.\n";
    loading(3500);
    cout << "  -Venha a mim e juntos vamos vencer essa guerra, CASTER!\n\n";
    loading(3000);
    cout << "Na mesma hora, um grande brilho faz voce fechar seus olhos por alguns instantes.\n";
    loading(3500);
    cout << "Quando abre seus olhos novamente, envolto a uma leve neblina, que antes nao estava la, esta uma jovem mulher.\n";
    loading(4500);
    cout << "Voce nao diria que ela tem mais do que 25 anos. Junto a sua aparencia jovem, estava um olhar um pouco recluso e cauteloso.\n\n";
    loading(4500);
    cout << "  -Suas palavras sao belas, mago. Espero ser digna delas em sua batalha.\n";
    loading(3500);
    cout << "  -Me chamo Anastasia, Anastasia Romanov, encantada.\n\n";
    loading(3000);
    cout << "  -Meu nome e " << nome << " e sera uma honra te-la ao meu lado.\n\n";
    loading(3000);
    cout << "Agora a sala estava mais clara, pois as nuvens no ceu sairam de frente da lua.\n";
    loading(3500);
    cout << "Gracas a isso, conseguiu perceber melhor como seu servo era.\n";
    loading(3000);
    cout << "Ela vestia um longo vestido branco com adornacoes em dourado. Em sua cabeca estava uma tiara, tambem dourada.\n";
    loading(4500);
    cout << "Sua pele e seu longo cabelo eram brancos como a neve, e seus olhos eram como o gelo azul.\n";
    loading(3500);
    cout << "Em suas maos estava uma especie de boneca de pele escura e cabelos loiros e, em suas costas, estava uma longa capa da cor de seus olhos.\n\n";
    loading(4500);
    cout << "  -Incrivel, realmente incrivel, quase invejavel! _ Disse Kirei aplaudindo lentamente\n";
    loading(3500);
    cout << "  -Porem, como ja avisei, seus inimigos nao irao esperar ate que toda a apresentacao acabe se continuar assim.\n";
    loading(4500);
    cout << "  -Aproveitem o final desta noite, afinal, nunca se sabe, essa pode ser sua ultima...\n\n";
    loading(3500);
    cout << "Mesmo em toda a situacao de guerra em que se encontra, a leve risada que Kirei deu ao final de sua frase ainda foi a coisa mais bizarra da noite\n";
    loading(4500);
    cout << "Apos uma leve despedida, voce e Anastasia saem da igreja em direcao ao centro de Fuyuki, onde estava hospedado.\n\n";
    loading(4500);
}

void escolha_rider(string nome) {
    cout << "\n  -Se deseja lutar ao lado do servo da classe Rider, " << nome << ", sei que ele tambem aceitara lutar ao seu lado.\n\n";
    loading(4500);
    cout << "  -Todos os preparativos para o ritual de invocacao estao prontos, vamos, apresse-se, pois seus inimigos nao irao te esperar!\n\n";
    loading(4500);
    cout << "Nisso, voce repara que toda a igreja ja estava preparada para o ritual, como se ate mesmo Kirei soubesse a classe escolhida antes de ti.\n";
    loading(4500);
    cout << "Porem, seu orgulho faz com que pense que isso eh apenas uma coincidencia.\n\n";
    loading(3500);
    cout << "  -Nao se assuste com a simplicidade, o ritual eh muito simples, pois quem faz a real invocacao eh o proprio Graal.\n\n";
    loading(4500);
    cout << "Realmente, o unico preparativo era um grande circulo cerimonial aos pes do altar com um objeto ao meio,\n";
    loading(4500);
    cout << "Porem, pela escuridao da noite, nao dava para perceber o que ele era.\n\n";
    loading(3000);
    cout << "  -Pois bem, eu " << nome << ", clamo que junte-se a mim a essa batalha.\n";
    loading(3500);
    cout << "  -Vamos vencer nossos inimigos e tomar aquilo que e nosso.\n";
    loading(3000);
    cout << "  -Nao por uma familia, por um grande bem ou por uma ordem.\n";
    loading(3000);
    cout << "  -Mas sim por nos mesmos, pelo nosso orgulho, pelo objetivo que guardamos em nossos coracoes.\n";
    loading(3500);
    cout << "  -Venha a mim e juntos vamos vencer essa guerra, RIDER!\n\n";
    loading(3000);
    cout << "Na mesma hora, um grande brilho faz voce fechar seus olhos por alguns instantes.\n";
    loading(3500);
    cout << "Quando abre seus olhos novamente, envolto a uma leve neblina, que antes nao estava la, esta um homem muito alto e musculoso.\n";
    loading(4500);
    cout << "Aparentava estar despreocupado e entusiasmado com a situacao.\n\n";
    loading(3000);
    cout << "  -HAHAHA, espero que voce seja tao bom em batalha quanto eh com as palavras, mago.\n";
    loading(3500);
    cout << "  -Me chamo Alexandre e juntos vamos conquistar, governar e mostra-los a forca de um imperador.\n\n";
    loading(3500);
    cout << "  -Meu nome e " << nome << " e sim, juntos conquistaremos a vitoria.\n\n";
    loading(3500);
    cout << "Agora a sala estava mais clara, pois as nuvens no ceu sairam de frente da lua.\n";
    loading(3000);
    cout << "Gracas a isso, conseguiu perceber melhor como seu servo era.\n";
    loading(3000);
    cout << "Ele vestia uma armadura cor de vinho e uma roupa vermelho vivo por baixo, junto a uma longa capa vermelha com adornacoes douradas.\n";
    loading(4500);
    cout << "Possuia um cabelo ruivo e curto, junto a uma barba. Em sua cintura, estava uma bainha com uma espada.\n";
    loading(4500);
    cout << "Estava tao focado em seu servo que mal percebeu que, no lado de fora, estava uma biga, esperando por voce e pelo Rider.\n\n";
    loading(4500);
    cout << "  -Incrivel, realmente incrivel, quase invejavel! _ Disse Kirei aplaudindo lentamente\n";
    loading(3500);
    cout << "  -Porem, como ja avisei, seus inimigos nao irao esperar ate que toda a apresentacao acabe se continuar assim.\n";
    loading(4500);
    cout << "  -Aproveitem o final desta noite, afinal, nunca se sabe, essa  pode ser sua ultima...\n\n";
    loading(3500);
    cout << "Mesmo em toda a situacao de guerra em que se encontra, a leve risada que Kirei deu ao final de sua frase ainda foi a coisa mais bizarra da noite\n";
    loading(4500);
    cout << "Apos uma leve despedida, voce e Alexandre saem da igreja em direcao ao centro de Fuyuki, onde estava hospedado.\n\n";
    loading(4500);
}

void escolha_berserker(string nome) {
    cout << "\n  -Se deseja lutar ao lado do servo da classe Berserker, " << nome << ", sei que ele tambem aceitara lutar ao seu lado.\n\n";
    loading(4500);
    cout << "  -Todos os preparativos para o ritual de invocacao estao prontos, vamos, apresse-se, pois seus inimigos nao irao te esperar!\n\n";
    loading(4500);
    cout << "Nisso, voce repara que toda a igreja ja estava preparada para o ritual, como se ate mesmo Kirei soubesse a classe escolhida antes de ti.\n";
    loading(4500);
    cout << "Porem, seu orgulho faz com que pense que isso eh apenas uma coincidencia.\n\n";
    loading(3500);
    cout << "  -Nao se assuste com a simplicidade, o ritual eh muito simples, pois quem faz a real invocacao eh o proprio Graal.\n\n";
    loading(4500);
    cout << "Realmente, o unico preparativo era um grande circulo cerimonial aos pes do altar com um objeto ao meio,\n";
    loading(4500);
    cout << "Porem, pela escuridao da noite, nao dava para perceber o que ele era.\n\n";
    loading(3000);
    cout << "  -Pois bem, eu " << nome << ", clamo que junte-se a mim a essa batalha.\n";
    loading(3500);
    cout << "  -Vamos vencer nossos inimigos e tomar aquilo que e nosso.\n";
    loading(3000);
    cout << "  -Nao por uma familia, por um grande bem ou por uma ordem.\n";
    loading(3000);
    cout << "  -Mas sim por nos mesmo, pelo nosso orgulho, pelo objetivo que guardamos em nossos coracoes.\n";
    loading(3500);
    cout << "  -Venha a mim e juntos vamos vencer essa guerra, BERSERKER!\n\n";
    loading(3000);
    cout << "Na mesma hora, um grande brilho faz voce fechar seus olhos por alguns instantes.\n";
    loading(3500);
    cout << "Quando abre seus olhos novamente, envolto a uma leve neblina, que antes nao estava la, esta uma mulher te encarando.\n";
    loading(4500);
    cout << "Um de seus olhos estava amarrado por uma bandagem, porem, dava para perceber claramente a seriedade em seu olhar.\n\n";
    loading(4500);
    cout << "  -Viver apenas por seu objetivo eh louvavel, entretanto, nada conseguimos por merito exclusivamente proprio.\n";
    loading(4500);
    cout << "  -Me chamo Florence Nightingale, serei leal as suas ordens e seguiremos unidos no campo de batalha.\n\n";
    loading(4500);
    cout << "  -Meu nome eh " << nome << " e garanto que sua lealdade nao sera em vao.\n\n";
    loading(3500);
    cout << "Agora a sala estava mais clara, pois as nuvens no ceu sairam de frente da lua.\n";
    loading(3500);
    cout << "Gracas a isso, conseguiu perceber melhor como seu servo era.\n";
    loading(3000);
    cout << "Ela vestia uma roupa militar vermelha, repousando uma jaqueta preta sobre seus ombros.\n";
    loading(3500);
    cout << "Seu cabelo era longo e branco e seus olhos eram vermelhos como sua roupa. Em sua cintura estava preso a um cinto dois kits verdes.\n";
    loading(4500);
    cout << "Ela tambem utilizava luvas brancas, junto a uma pistola de percussao antiga.\n\n";
    loading(3500);
    cout << "  -Incrivel, realmente incrivel, quase invejavel! _ Disse Kirei aplaudindo lentamente\n";
    loading(3500);
    cout << "  -Porem, como ja avisei, seus inimigos nao irao esperar ate que toda a apresentacao acabe se continuar assim.\n";
    loading(4500);
    cout << "  -Aproveitem o final desta noite, afinal, nunca se sabe, essa  pode ser sua ultima...\n\n";
    loading(3500);
    cout << "Mesmo em toda a situacao de guerra em que se encontra, a leve risada que Kirei deu ao final de sua frase ainda foi a coisa mais bizarra da noite\n";
    loading(4500);
    cout << "Apos uma leve despedida, voce e Nightingale saem da igreja em direcao ao centro de Fuyuki, onde estava hospedado.\n\n";
    loading(4500);
}

void escolha_assassin(string nome) {
    cout << "\n  -Se deseja lutar ao lado do servo da classe Assassin, " << nome << ", sei que ele tambem aceitara lutar ao seu lado.\n\n";
    loading(4500);
    cout << "  -Todos os preparativos para o ritual de invocacao estao prontos, vamos, apresse-se, pois seus inimigos nao irao te esperar!\n\n";
    loading(4500);
    cout << "Nisso, voce repara que toda a igreja ja estava preparada para o ritual, como se ate mesmo Kirei soubesse a classe escolhida antes de ti.\n";
    loading(4500);
    cout << "Porem, seu orgulho faz com que pense que isso eh apenas uma coincidencia.\n\n";
    loading(3500);
    cout << "  -Nao se assuste com a simplicidade, o ritual eh muito simples, pois quem faz a real invocacao eh o proprio Graal.\n\n";
    loading(4500);
    cout << "Realmente, o unico preparativo era um grande circulo cerimonial aos pes do altar com um objeto ao meio,\n";
    loading(4500);
    cout << "Porem, pela escuridao da noite, nao dava para perceber o que ele era.\n\n";
    loading(3000);
    cout << "  -Pois bem, eu " << nome << ", clamo que junte-se a mim a essa batalha.\n";
    loading(3000);
    cout << "  -Vamos vencer nossos inimigos e tomar aquilo que e nosso.\n";
    loading(3000);
    cout << "  -Nao por uma familia, por um grande bem ou por uma ordem.\n";
    loading(3000);
    cout << "  -Mas sim por nos mesmo, pelo nosso orgulho, pelo objetivo que guardamos em nossos coracoes.\n";
    loading(4500);
    cout << "  -Venha a mim e juntos vamos vencer essa guerra, ASSASSIN!\n\n";
    loading(3000);
    cout << "Na mesma hora, um grande brilho faz voce fechar seus olhos por alguns instantes.\n";
    loading(3500);
    cout << "Quando abre seus olhos novamente, envolto a uma leve neblina, que antes nao estava la, esta um jovem homem.\n";
    loading(4500);
    cout << "Da para perceber que ele ficava te encarando e, em um piscar de olhos, ele aparece atras de voce e fala perto do seu ouvido.\n\n";
    loading(4500);
    cout << "  -Uma boa labia para um bom mago. Mas belas palavras nao sao o bastante em uma batalha.\n";
    loading(3500);
    cout << "  -Me chamo Charles-Henri, e serei o carrasco de seus inimigos.\n\n";
    loading(3000);
    cout << "  -Meu nome e " << nome << " e juntos, venceremos essa guerra.\n\n";
    loading(3000);
    cout << "Agora a sala estava mais clara, pois as nuvens no ceu sairam de frente da lua.\n";
    loading(3500);
    cout << "Gracas a isso, conseguiu perceber melhor como seu servo era.\n";
    loading(3000);
    cout << "Ele vestia uma camisa branca, com uma gravata vermelha e um sobretudo escuro.\n";
    loading(3500);
    cout << "Seu cabelo era branco e curto. Seus olhos eram azul ciano e sua feicao era despreocupada, porem assustadora.\n";
    loading(4500);
    cout << "Ao seu lado estava uma grande e longa espada negra. Voce tambem nao deixa de perceber o sorriso presuncoso em sua face.\n\n";
    loading(4500);
    cout << "  -Incrivel, realmente incrivel, quase invejavel! _ Disse Kirei aplaudindo lentamente\n";
    loading(3500);
    cout << "  -Porem, como ja avisei, seus inimigos nao irao esperar ate que toda a apresentacao acabe se continuar assim.\n";
    loading(4500);
    cout << "  -Aproveitem o final desta noite, afinal, nunca se sabe, essa  pode ser sua ultima...\n\n";
    loading(4500);
    cout << "Mesmo em toda a situacao de guerra em que se encontra, a leve risada que Kirei deu ao final de sua frase ainda foi a coisa mais bizarra da noite\n";
    loading(4500);
    cout << "Apos uma leve despedida, voce e Charles-Henri saem da igreja em direcao ao centro de Fuyuki, onde estava hospedado.\n\n";
    loading(4000);
}

void batalha_assassin(string nome) {
    cout << "\nApos os acontecimentos do ultimo dia, sua noite de sonho nao foi das melhores.\n";
    loading(3500);
    cout << "Porem, conseguiu dormir o suficiente para descansar, enquanto seu servo ficava de vigia.\n";
    loading(3500);
    cout << "Voce se levanta, troca de roupa sai para comer alguma coisa em uma padaria proxima.\n";
    loading(3500);
    cout << "Seu servo senta-se ao seu lado para acompanha-lo, o que te provoca a seguinte duvida:\n\n";
    loading(3500);
    cout << "  -Voces espiritos heroicos sao alimentados pela nossa mana, dos mestres.\n";
    loading(3500);
    cout << "  -Porque entao divide a mesa comigo?\n";
    loading(3000);
    cout << "  -Apenas para deixar a conta mais cara? Nao sou tao rico se e o que pensa.\n";
    loading(3000);
    cout << "  -Posso nao precisar me alimentar, porem a comida ainda tem o mesmo sabor. E deliciosa!\n\n";
    loading(3500);
    cout << "O clima amenuo da conversa logo acaba com uma carta que apareceu ao seu lado, sem ao menos perceber.\n";
    loading(4500);
    cout << "Nela estava escrito \"Espero que esteja aproveitando a tranquilidade momentanea.\" \n";
    loading(3500);
    cout << "Nisso voce olha para a porta do lugar e ve uma mulher ruiva, de oculos escuros, calca jeans e uma regata vermelha.\n";
    loading(4500);
    cout << "Quando ela sai de seu campo de visao, voce logo se levanta, deixa dinheiro em cima da mesa e corre atras dela.\n";
    loading(4500);
    cout << "Apos cerca de 30min de perseguicao, ela finalmente para de correr de ti.\n";
    loading(3500);
    cout << "Voces estao ao norte de Fuyuki, na entrada de uma foresta, com nenhuma pessoa a sua volta alem de voces.\n\n";
    loading(4500);
    cout << "  -Vejo que tem coragem por me seguir ate aqui, " << nome << ". Porem, apenas coragem nao te ajudara.\n";
    loading(4500);
    cout << "  -Assassin, ensine boas maneiras para nossos convidados.\n\n";
    loading(3000);
    cout << "  -Mas e claro, mademoiselle.\n\n";
    loading(3000);
    cout << "Nisso voce sente uma brisa leve nas suas costas e desvia no mesmo instante, vendo uma grande espada no lugar onde antes estava seu pescoco.\n\n";
    loading(4500);
    cout << "  -Entao voce e do tipo que fica desviando, mas que sem graca.\n\n";
    loading(3000);
    cout << "O Assassin era um jovem de cabelos brancos e olhos azuis, com um sobretudo negro e uma grande espada de mesma cor.\n\n";
    loading(4500);
    cout << "  -Prazer, sou Charles-Henri, porem agora, serei exclusivamente o carrasco de voces.\n\n";
    loading(3500);
    cout << "E com isso, a batalha comeca!\n\n";
    loading(3000);

}

void derrota_assassin() {
    cout << "Assim o mestre do Assassin percebe a inevitavel derrota, ela sai correndo em meio a floresta.\n";
    loading(3500);
    cout << "Voce pensa em correr atras dela, porem, nao vale a pena o esforco.\n";
    loading(3000);
    cout << "Nisso, seu servo ja aparece atras de voce, enquanto o corpo de Charles-Henri estava ao meio de varias arvores derrubadas.\n";
    loading(4500);
    cout << "Vendo o corpo do Assassin dessaparecer aos poucos, voce comeca a andar calmamente, voltando para a cidade.\n";
    loading(4500);
    cout << "Seu servo vem logo atras de ti, enquanto sentiam o calor da tarde de outono.\n\n";
    loading(3000);
}

void batalha_saber(string nome) {
    cout << "No caminho de volta para onde estava hospedado, voce e seu servo passam por um parque, ao leste de Fuyuki\n";
    loading(4500);
    cout << "Caminhando tranquilamente a beira de um lago, ja perdendo a nocao de de horario.\n";
    loading(3500);
    cout << "Nisso voce sente uma forte presenca no lado oposto ao que tu estava.\n";
    loading(3000);
    cout << "Do outro lado do lago, havia um jovem rapaz loiro de cabelo curto, nao muito alto.\n";
    loading(3500);
    cout << "Vestia roupas comuns para alguem da sua idade, uma jaqueta azul com uma blusa branca por baixo e jeans.\n";
    loading(4500);
    cout << "Ele estava tao calmo caminhando a beira do lado que voce se sente calmo tambem.\n";
    loading(3500);
    cout << "Porem, seu servo nao tira os olhos dele, como se esperasse um ataque iminente.\n";
    loading(3500);
    cout << "Isso faz com que voce tambem fique atento.\n\n";
    loading(3000);
    cout << "  -Ah, desculpa atrapalhar, voces estavam tao tranquilos caminhando, nao queria acabar com o momento.\n\n";
    loading(3500);
    cout << "Disse o rapaz, com um sorriso leve no rosto, porem com uma feicao realmente de arrependimento.\n\n";
    loading(3500);
    cout << "  -Enfim..._Nisso ele atravessa todo o lago em um pulo, como se fosse algo trivial.\n";
    loading(3500);
    cout << "  -Voce deve ser o " << nome << ", certo?\n";
    loading(3000);
    cout << "  -E esse pelo visto eh seu servo. Bem, prazer, meu nome e Arthur.\n\n";
    loading(3000);
    cout << "Ele se apresenta com um sorriso no rosto, mostrando nenhuma hostilidade.\n";
    loading(3000);
    cout << "Ao longe podemos ver um homem por volta dos 30 anos.\n";
    loading(3000);
    cout << "Vestia uma camisa branca com uma jaqueta azul por cima e jeans.\n";
    loading(3000);
    cout << "Tinha cabelo escuro e preso por ser grande, alem de olhos claros fixos em voce.\n\n";
    loading(3000);
    cout << "  -Entao voce ja encontrou nossos amigos, Arthur. Eai, como estao?\n\n";
    loading(3000);
    cout << "Mesmo nao havendo hostilidade em suas falas, seu olhar era direto e frio, demonstrava nada, quase vazio.\n\n";
    loading(4500);
    cout << "  -Eh uma pena que tenhamos nos conhecido nessa situacao..._Ele diz isso enquanto acende um cigarro.\n";
    loading(4500);
    cout << "  -Vamos terminar isso Arthur.\n\n";
    loading(3000);
    cout << "Nisso, o servo da classe Saber olha para voces e, em um piscar de olhos, aparece com uma armadura completa\n";
    loading(4500);
    cout << "Seu servo fica a sua frente e se prepara para a batalha que vai comecar.\n\n";
    loading(3000);
}

void derrota_saber() {
    cout << "Apos essa intensa batalha, Arthur se encontrava desacordado em meio ao lago\n";
    loading(3500);
    cout << "Enquando isso, seu mestre estava deitado em uma arvore ao lado, com um grande ferimento no abdomen.\n";
    loading(4500);
    cout << "Voce vai andando em direcao, para por um fim a dor dele.\n\n";
    loading(3500);
    cout << "  -Espere!_Nisso ele tira um cigarro do bolso e coloca em sua boca_-Tem isqueiro?\n\n";
    loading(3500);
    cout << "Mesmo diante da situacao, voce abre um leve sorriso.\n";
    loading(3000);
    cout << "Pega um isqueiro do seu bolso e acende o cigarro do outro mago.\n";
    loading(3000);
    cout << "Logo apos, voce saca uma pistola que estava guardada em sua cintura e atira no mestre derrotado.\n";
    loading(3500);
    cout << "Seu servo observa de longe, e ao perceber que o corpo do Saber nao estava mais no lago, voces saem do parque.\n\n";
    loading(4000);
}

void batalha_caster() {
    cout << "2 dias se passaram desde o ultimo dia.\n";
    loading(3000);
    cout << "Voce ficou atento a qualquer movimento ou acao suspeita, porem, seus dias foram normais.\n";
    loading(3500);
    cout << "Seu servo ficou de vigia durante as noites e mesmo ele notou nada de diferente.\n";
    loading(3500);
    cout << "Nesse tempo de calmaria, voce comecou a estudar mais sobre os possiveis mestres.\n";
    loading(3500);
    cout << "Ficou atento as noticias para encontrar novidades, mas sempre era mais do mesmo.\n";
    loading(3500);
    cout << "Em um desses dias de pesquisa, voce foi ate a biblioteca municipal.\n";
    loading(3500);
    cout << "Ela como sempre estava muito calma e cheia de estudantes.\n";
    loading(3000);
    cout << "Voce acabou se perdendo em suas pesquisas e ficou la ate tarde da noite, quando todos ja haviam ido embora.\n\n";
    loading(4500);
    cout << "  -Eles estao quase fechando, acho melhor sair por hoje_Disse um jovem que estava se levantando da mesa ao lado.\n\n";
    loading(4500);
    cout << "Voce se assusta, pois nao havia notado a presenca dele ali, porem concorda com a cabeca e se levanta tambem.\n";
    loading(4500);
    cout << "O jovem parecia ter seus 20 anos, nao muito alto e tinha barba e cabelos castanhos.\n";
    loading(3500);
    cout << "Antes de sair, ele parou para reservar um livro sobre anatomia, e pediu para que voce o esperasse.\n";
    loading(4500);
    cout << "Mesmo sendo um dia muito frio, voce acabou por espera-lo.\n";
    loading(3000);
    cout << "O que mais te intrigou e que ele nao tinha aparencia japonesa, o que era incomum pelo o que havia visto.\n";
    loading(4500);
    cout << "Nisso ele voces acabam conversando ate chegarem perto de um templo abandonado.\n\n";
    loading(3500);
    cout << "  -Agora voce vai dizer o que realmente quer?_Voce o repreende, interompendo a conversa amigavel.\n";
    loading(4500);
    cout << "  -Nao seja assim, a nossa conversa estava tao interessante._Diz ele, parecendo realmente desapontado.\n";
    loading(4500);
    cout << "  -Sei que nada do que eu dizer vai mudar o que vai acontecer agora, eh algo que se deve fazer, nao eh mesmo?\n";
    loading(4500);
    cout << "  -Caster!_Assim que completou sua fala, uma jovem apareceu repentinamente ao seu lado.\n\n";
    loading(3500);
    cout << "Ela parecia ter a mesma idade que ele, talvez ate mais jovem.\n";
    loading(3000);
    cout << "Vestia roupas brancas de inverno e seus cabelos eram longos de mesma cor, alem de seus olhos que eram como gelo azul.\n";
    loading(4500);
    cout << "No mesmo instante, seu servo apareceu ao seu lado, pois estava te vigiando todo esse tempo.\n\n";
    loading(3500);
    cout << "  -Bem, meu nome e Alisson, e essa eh a Anastasia.\n\n";
    loading(3000);
    cout << "Mesmo Anastasia parecendo uma jovem receosa, seus olhos estavam fixos em voce e seu servo, com uma feicao seria.\n";
    loading(4500);
    cout << "E, com isso, a luta entre voces comeca!\n\n";
    loading(3000);
}

void derrota_caster() {
    cout << "Anastasia estava desmaiada nas escadarias do templo, no meio do terreno todo destruido.\n";
    loading(3500);
    cout << "Seu mestre foi correndo para ve-la.\n";
    loading(3000);
    cout << "Quando viu suas feridas e que estava desmaiada, tentou cura-la, porem, em vao.\n";
    loading(3500);
    cout << "O corpo da Caster comecou a desaparecer lentamente em seus bracos.\n";
    loading(3000);
    cout << "Voce o encara por alguns segundos e sai andando de volta para a cidade.\n";
    loading(3500);
    cout << "Seu servo vai logo atras de ti, concordando com sua decisao de deixa-lo la.\n";
    loading(3500);
    cout << "Nisso, voces voltam para onde estao hospedados, guardando aquela cena em suas mentes.\n\n";
    loading(3000);
}

void batalha_berserker(string nome) {
    cout << "Tudo que aconteceu no outro dia ainda atormentava sua mente.\n";
    loading(3000);
    cout << "Como uma forma de ficar menos preocupado, passou varias horas conversando com seu servo.\n";
    loading(3500);
    cout << "Conheceu mais sobre sua historia, detalhes que estavam em nenhum livro.\n";
    loading(3000);
    cout << "A conversa estava muito agradavel, por um momento esqueceu do destino que estavam enfrentando.\n";
    loading(3500);
    cout << "Em meio a conversa uma carta entrou em seu quarto pela janela aberta; nela estava escrito:\n\n";
    loading(3500);
    cout << "Caro " << nome << ", venha ao local que os enredos encontram com o ponto final.\n\n";
    loading(3500);
    cout << "Voce e seu servo trocaram olhares preocupados e sairam logo em seguida.\n";
    loading(3500);
    cout << "Apos algum tempo, chegaram ate o local, o cemiterio municipal, que por algum motivo estava interditado.\n";
    loading(4500);
    cout << "Entraram no local, que aparentava estar todo deserto.\n";
    loading(3000);
    cout << "Nisso voces veem uma mulher ajoelhada em frente a um tumulo, prestando homenagem.\n";
    loading(3500);
    cout << "Ao lado dela ha um senhor, por volta de seus 70 anos.\n\n";
    loading(3000);
    cout << "  -Diga-me " << nome << ", o que todas historias tem em comum?_Pergunta o homem.\n\n";
    loading(3500);
    cout << "  -Elas acabam._Voce responde logo em seguida.\n\n";
    loading(3000);
    cout << "Voce pode observar melhor a situacao, o senhor vestia um terno completo, completamente preto.\n";
    loading(3500);
    cout << "Ja a mulher vestia uma roupa vermelha, parecendo militar, com uma jaqueta pendurada nas costas.\n";
    loading(3500);
    cout << "Possuia uma bandagem em volta de seu olho direito e seus cabelos eram brancos e longos.\n";
    loading(3500);
    cout << "Apos seu dialogo com o senhor, ela se levantou rapidamente, porem seu mestre a repreende:\n\n";
    loading(3500);
    cout << "  -Tenha calma, Berserker. Bem, essa e Florence Nightingale, da Classe Berserker, como comentei.\n";
    loading(3500);
    cout << "  -Acredito que conhecam sua historia, eh realmente um encanto lutar ao lado dela.\n";
    loading(3500);
    cout << "  -Mas bem, nao vou mais tirar seu tempo, sei o quanto ele e importante.\n\n";
    loading(3000);
    cout << "Nisso, voce e o seu servo se preparam para a batalha que esta por vir.\n\n";
    loading(3000);
}

void derrota_berserker() {
    cout << "Em meio a explosoes de tumulos, Nightingale se encontra quase desacordada, caida no chao.\n";
    loading(3500);
    cout << "Enquanto isso, seu mestre, ja exausto da batalha, assistia os ultimos momentos, sem poder fazer nada.\n";
    loading(4500);
    cout << "Nisso, seu servo finaliza a Berserker e voce caminha em direcao a saida do cemiterio.\n\n";
    loading(3500);
    cout << "  -Espere!_Diz o senhor, ja mal aguentando ficar em pe.\n";
    loading(3000);
    cout << "  -Finalize o que comecou, mago.\n\n";
    loading(3000);
    cout << "  -Nao tenho essa obrigacao, fique com o amanha que te pertence._Voce retruca em sequencia.\n\n";
    loading(3500);
    cout << "Nisso o senhor com uma expressao de acabado diz: \n\n";
    loading(3000);
    cout << "  -O amanha eh apenas uma esperanca, nunca uma promessa.\n\n";
    loading(3000);
    cout << "  -Entao nao temes a morte?\n\n";
    loading(3000);
    cout << "  -Aceitar a vida significa abracar a morte, nao tenho arrependimentos. A verdadeira morte eh nunca ter vivido.\n\n";
    loading(4500);
    cout << "Apos as palavras do nobre senhor, voce saca sua arma e atira nele, matando-o com apenas um tiro.\n";
    loading(3500);
    cout << "Nisso, voce e seu servo saem do cemiterio, voltando para onde estava hospedados.\n\n";
    loading(3000);
}

void batalha_lancer() {
    cout << "O ultimo dia foi bastante estressante, tanto para voce quanto para o seu servo.\n";
    loading(3500);
    cout << "Por isso, decidiu sair um pouco do padrao.\n";
    loading(3000);
    cout << "Comecou a visitar os pontos turisticos de Fuyuki, agir como um turista normalmente agiria.\n";
    loading(3500);
    cout << "Seu servo te acomponhou durante toda viagem, e parecia estar aproveitando tanto quanto voce.\n";
    loading(3500);
    cout << "Nisso, voces decidiram ir a uma peca teatral que teria naquela noite.\n";
    loading(3500);
    cout << "Vestiram roupas apropriadas para a ocasiao se escolheram os melhores lugares do teatro.\n";
    loading(3500);
    cout << "O espetaculo durou cerca de 2 horas e voce se espantou com o talento dos atores.\n";
    loading(3500);
    cout << "Assim que a peca acabou, voce conseguiu ir visitar os atores e os parabenizou pela apresentacao.\n";
    loading(3500);
    cout << "Nisso foi convidado para uma festa que teria depois, mas acabou recusando, aquilo ja era demais.\n";
    loading(3500);
    cout << "Porem o ator principal pareceu irritado com a recusa e pediu que ao menos fosse ao camarim para comer algo.\n";
    loading(4500);
    cout << "Como ja avisa recusado um convite, nao queria dizer nao novamente e acabou aceitando.\n";
    loading(3500);
    cout << "Chegando ao camarim, o ator selou a porta com uma magia e ja disse em seguida:\n\n";
    loading(3500);
    cout << "  -Nossa como foi dificil arrumar um tempo contigo.\n";
    loading(3000);
    cout << "  -Ah, e nem pense em fazer algo sem pensar, lembre de quantas pessoas estao nesse teatro agora.\n";
    loading(4000);
    cout << "  -Lancer, venha dizer ola aos nosso convidados.\n\n";
    loading(3000);
    cout << "Nisso, um jovem homem alto, com um cabelo azul preso a um rabo de cavalo e vestindo uma armadura leve aparece.\n\n";
    loading(4500);
    cout << "  -Voces ja conhecerem meu mestre, e eu, bem, me chamo Cu Chulainn, que nossa batalha seja lembrada.\n\n";
    loading(4500);
    cout << "Seus olhos eram vermelhos e estavam fixos olhando para ti.\n";
    loading(3000);
    cout << "No mesmo instante, seu servo aparece na sua frente, interceptando os olhares do Lancer.\n";
    loading(3500);
    cout << "Apos cerca de 30 minutos se encarando, ambos perceberam que nao havia mais ninguem no teatro.\n";
    loading(3500);
    cout << "Nesse momento seus servos ja entram em combate, destruindo a sala que estavam.\n";
    loading(3500);
    cout << "Sua batalha acabou de comecar!\n\n";
    loading(3000);
}

void derrota_lancer() {
    cout << "Todo o teatro estava destruido apos a batalha, voce sabia que nao podia ficar la por muito mais tempo.\n";
    loading(4500);
    cout << "O mestre do Lancer estava desacordado no meio do palco, possivelmente ja morto.\n";
    loading(3500);
    cout << "Enquanto isso, o Lancer estava no meio das cadeiras da plateia, todas destruidas pelo impacto.\n";
    loading(3500);
    cout << "Voce observa seu servo finalizar o Lancer logo em seguida.\n";
    loading(3000);
    cout << "Nisso voces logo saem do teatro, e, depois de pouco minutos apos terem saido, escutam ao longe o barulho dele desmoronando.\n";
    loading(4500);
    cout << "Apos ficar algum tempo por volta, para confirmar que nao haviam suspeitas em cima de ti sobre o ocorrido, voce volta para onde estava hospedado.\n\n";
    loading(4000);
}

void batalha_rider() {
    cout << "Em meio a sua pesquisa sobre noticias fora do usual na cidade, voce descobre sobre um estranho homem que andava pela cidade.\n";
    loading(4500);
    cout << "Era um homem ridiculamente alto e forte, com barba e cabelo ruivos.\n";
    loading(3000);
    cout << "Pesquisando mais sobre, voce descobre que ele sempre visita um cafe no centro da cidade pela manha.\n";
    loading(4500);
    cout << "No outro dia, voce vai junto com o seu servo a esse cafe.\n";
    loading(3000);
    cout << "Voces encontram esse homem la, comendo tranquilamente ao lado de um jovem, que aparentava ter seus 20 anos.\n";
    loading(4500);
    cout << "Mesmo com a situacao pouco usual, voce senta na mesma mesa que eles e seu servo senta ao seu lado.\n\n";
    loading(4500);
    cout << "  -Um pouco deselegante, vindo interromper dois homens no meio de uma refeicao._Disse o grande homem.\n\n";
    loading(4500);
    cout << "  -Nao me entenda errado, nao quero atrapalhar. Usem o tempo que precisarem._Voce responde em sequencia.\n\n";
    loading(4500);
    cout << "Enquanto comiam, voce pode perceber claramente que o jovem era o mestre, enquanto o ruivo era o seu servo.\n";
    loading(4500);
    cout << "Logo apos a refeicao, voces se levantam e andam pela cidade.\n";
    loading(3000);
    cout << "Passam-se varios minutos de caminhada, ate que saem da cidade, andando por uma estrada perto de uma parte com grande vegetacao.\n";
    loading(4500);
    cout << "Nisso, eles param de caminham, e o homem diz: \n";
    loading(3000);
    cout << "  -Aqui ja esta bom, afinal, nao queremos confusao com outras pessoas por perto nao eh mesmo?\n";
    loading(3500);
    cout << "  -Me chamo Alexandre, e esse jovem poderoso mago, eh meu mestre!!\n\n";
    loading(3500);
    cout << "Ao dizer isso, da um leve tapa nas costas do jovem, que quase faz ele cair. Pareciam se dar muito bem.\n";
    loading(4500);
    cout << "Apos isso, voces se encararam por alguns segundos e, em seguida, a batalha comeca.\n\n";
    loading(3000);
}

void derrota_rider() {
    cout << "A batalha estava intensa, sorte que estavam longe de qualquer outra pessoa.\n";
    loading(3500);
    cout << "Enquanto seu servo lutava contra Alexandre, junto ao seu suporte, voce tenta atirar no mestre do Rider.\n";
    loading(4500);
    cout << "Vendo essa cena, o Rider entra na frente para defende-lo de seu tiro.\n";
    loading(3500);
    cout << "Seu servo aproveita a aportunidade criada e finaliza o servo inimigo na mesma hora, na frente de seu mestre.\n";
    loading(4500);
    cout << "O jovem parecia nao acreditar no que estava acontecendo, porem, aguentou toda a situacao e se levantou como se ainda quisesse lutar.\n\n";
    loading(4500);
    cout << "  -Sua batalha ja acabou._Voce responde na mesma hora.\n";
    loading(3000);
    cout << "  -Nao desperdice a vida que Alexandre lutou para proteger.\n\n";
    loading(3000);
    cout << "Nisso, voce e seu servo partem de volta para a cidade, deixando o jovem mago sozinho no campo.\n\n";
    loading(3000);
}

void batalha_archer() {
    cout << "Enquanto voltava para o local que estava alojado, voce decide passar perto do porto.\n";
    loading(3500);
    cout << "A brisa do mar sempre era algo que te acalmava, pois te trazia boas lembrancas de sua antiga casa.\n";
    loading(3500);
    cout << "Enquanto as memorias vinham a tona, pensava se ainda conseguiria voltar para ela depois que tudo isso acabasse.\n";
    loading(3500);
    cout << "Enquanto isso, seu servo olhava para o oceano com a mesma feicao que voce estava.\n";
    loading(3500);
    cout << "Nisso tu se pergunta se as coisas que passam pela cabeca dele sao as mesmas que se passavam pela sua.\n";
    loading(4500);
    cout << "Se ele tambem sentia falta de sua casa, das suas origens.\n";
    loading(3000);
    cout << "Enquanto esses pensamentos leves te tomavam, voces escutam uma explosao vinda do meio da area de descarga do porto.\n";
    loading(4500);
    cout << "Voce e seu servo se encaram por alguns instantes e decidem ir ver o que estava acontecendo.\n";
    loading(3500);
    cout << "Chegando no local da explosao, que estava com varias placas interditando o local, voces avistam um homem.\n";
    loading(4500);
    cout << "Ele segurava um canhao gigante, quase da sua propria altura, e usava ele para explodir pequenas coisas.\n";
    loading(4500);
    cout << "Enquanto ele ria toda vez que acertava um alvo, uma jovem mulher ficava anotando em uma placa a quantidade de acertos.\n";
    loading(4500);
    cout << "Depois do homem atirar, chegava a vez dela tentar acertar um alvo com sua sua arma, pareciam estar se divertindo bastante com aquilo.\n\n";
    loading(4500);
    cout << "  -Acho que ja deu por hoje, Archer. Afinal, temos visitas._Disse a jovem, olhando para o lugar onde estavam escondidos.\n\n";
    loading(4500);
    cout << "Voce sai do seu esconderijo e da uma leve risada.\n\n";
    loading(3000);
    cout << "  -Quer participar da competicao?_Pergunta a jovem, parecendo realmente empolgada com a ideia.\n\n";
    loading(3500);
    cout << "  -Desculpa, mas se eu participasse voces nao teriam a menor chance, entao acho melhor nao._Voce responde, ainda com um leve sorriso no rosto.\n\n";
    loading(4500);
    cout << "Nisso, o homem com o canhao, aparentemente o servo da mulher, responde: \n\n";
    loading(3500);
    cout << "  -Voces deviam aprender a serem mais humildes, nao conquistaria metade do que conquistei com atitudes assim.\n";
    loading(4500);
    cout << "  -Essa aqui agiu da mesma forma, agora esta perdendo por 5 pontos._Ele diz isso com extremo orgulho.\n";
    loading(4500);
    cout << "  -Me chamo Napoelao, mas aqui, permito que me chamem apenas de Archer.\n\n";
    loading(3500);
    cout << "Mesmo com a situacao descontraida, voce sabia como aquilo tudo acabaria.\n";
    loading(3500);
    cout << "Seu servo ja estava preparado logo atras de ti.\n";
    loading(3000);
    cout << "Nisso a feicao da jovem muda completamente, ficando seria e te encarando com olhos frios.\n";
    loading(3500);
    cout << "Apos alguns segundos, que pareciam uma eternidade, a jovem ordena que Napoleao te atacasse, mas seu  servo interrompe o ataque.\n";
    loading(4500);
    cout << "Com isso, a batalha comeca!\n\n";
    loading(3000);
}

void derrota_archer() {
    cout << "A batalha contra Napoelao foi mais intensa do que voce pensou que seria, porem o resultado foi inevitavel.\n";
    loading(4500);
    cout << "O corpo do servo da classe Archer estava caido no meio do porto e seu canhao estava quebrado, longe dele.\n";
    loading(4500);
    cout << "Sua mestre estava caida perto dele, ja morta apos receber um golpe de seu servo durante a batalha.\n\n";
    loading(4500);
    cout << "  -Ela era uma boa jovem._Disse Napoleao, ja mal aguentando ficar de pe.\n";
    loading(3000);
    cout << "  -Mas e como eu disse, atitudes com excesso de confianca nao te levam muito longe, eh uma pena\n";
    loading(3500);
    cout << "  -Tome cuidado tambem, mago. Voce nao sabe o que o destino te reserva.\n\n";
    loading(3000);
    cout << "Apos essas palavras, seu servo finalizou o Archer, restando apenas o silencio onde estavam.\n";
    loading(3500);
    cout << "Assim, voce e seu servo saem do porto, e caminham para casa apos a batalha.\n\n";
    loading(3000);
}

bool endgame(string nome){
    int escolha;

    cout << "\n\n======================== THE END ========================\n\n";
    loading(3500);
    cout << "Voce ja venceu todos os outros mestres e seus servos, porem algo ainda parecia estar errado.\n";
    loading(3500);
    cout << "Mesmo assim, voce e seu servo passaram por muitas situacoes dificeis e provacoes arduas para chegar ate aqui.\n";
    loading(4500);
    cout << "Voces mereciam o Santo Graal, afinal, provaram serem os mais fortes.\n";
    loading(3500);
    cout << "Porem, uma inseguranca imensa atormentava o seu coracao.\n\n";
    loading(3500);
    cout << "  ~ Sera que acabou? Isso foi o bastante? Ainda sou digno depois de tudo que aconteceu? ~ \n\n";
    loading(3500);
    cout << "Esses pensamentos nao saiam de sua mente e te atormentavam todo instante.\n";
    loading(3500);
    cout << "Seu servo parecia estar com preocupacoes similares, parecendo inquieto.\n\n";
    loading(3500);
    cout << "---------------------------------------------------------------------------\n\n";
    loading(3500);
    cout << "Apos nao aguentar mais esperar em seu quarto, voce acaba indo para a igreja onde tudo comecou para falar com Kirei\n";
    loading(4500);
    cout << "Durante a caminhada, voce observa a lua cheia ao longe e sente um vento frio de outono.\n";
    loading(3500);
    cout << "Porem, os ventos nao eram agradaveis como os da primeira vez que esteve nesse caminho.\n";
    loading(3500);
    cout << "Que horas eram? Nao tinha ideia, nem mesmo olhando para a lua conseguia estipular um horario.\n";
    loading(3500);
    cout << "Ao chegar em frente a igreja, voce observa um homem com roupas negras em frente dela, te esperando.\n\n";
    loading(4500);
    cout << "Logo vc percebe que eh  Kirei Kotomine, e ele logo diz:\n\n";
    loading(3000);
    cout << "  -Sempre tive todas as minhas esperancas em voce, " << nome << ".\n";
    loading(3500);
    cout << "  -Entre, precisamos conversar. Porem..._Ele encara o seu servo por alguns segundos.\n";
    loading(3500);
    cout << "  -Venha sozinho, acredito que um Espirito Heroico nao tera problemas em esperar um pouco.\n\n";
    loading(3500);
    cout << "Voce e seu servo se olham por alguns instantes.\n";
    loading(3000);
    cout << "As palavras de Kirei te incomodaram profundamente, porem, nao via outra escolha e aceitou entrar sozinho na igreja.\n";
    loading(3500);
    cout << "A luz da lua iluminava os vidrais da igreja, dando uma alta claridade ao local.\n";
    loading(3500);
    cout << "Kirei para em frente ao altar fica algum tempo olhando para cima, enquanto voce espera logo atras.\n\n";
    loading(4500);
    cout << "  -Sabe, " <<nome<<", essa guerra pelo graal sempre eh mais complicada do que aparenta.\n";
    loading(3500);
    cout << "  -Voce sabe que nao eh voce ou eu que faz a invocacao do servo, mas sim o proprio graal, nao eh mesmo?\n\n";
    loading(4500);
    cout << "Voce concorda com a cabeca, sem entender bem onde que quer chegar com isso.\n\n";
    loading(3500);
    cout << "  -Bem, os servos realmente sao magnificos. Pessoas de grande importancia, ate mesmo pessoas que nunca existiram.\n";
    loading(4500);
    cout << "  -Pessoas miticas, personagens de lendas, lutando ao seu lado. Eh uma experiencia unica, um poder inestimavel!\n";
    loading(4500);
    cout << "  -Porem, ate mesmo para o Graal, essa invocacao eh algo que consome muita energia magica, entende o que quero dizer?\n\n";
    loading(4500);
    cout << "Voce estava mais confuso do que nunca, nao entende ate onde Kirei quer chegar com essa logica.\n\n";
    loading(3500);
    cout << "  -O que quero dizer eh que, o Graal nunca ficara completo enquanto estiver algum servo vivo usando a sua energia.\n\n";
    loading(4500);
    cout << "Enquanto dizia essas ultimas palavras, ele apontava de leve para o lado de fora da igreja, onde o seu servo esta te esperando.\n\n";
    loading(4500);
    cout << "  -E o que voce espera que eu faca?_Voce pergunta para Kirei.\n\n";
    loading(3500);
    cout << "  -Bem..._Ele responde\n";
    loading(3000);
    cout << "  -Voces, mestres, possuem uma autoridade sobre seu seus servos, podendo dar um comando que eh impossivel que eles desobedecam.\n";
    loading(4500);
    cout << "  -E nao tem como utilizar o Graal se ele permanecer vivo.\n";
    loading(3500);
    cout << "  -Logo, ha apenas uma escolha obvia: \n";
    loading(3000);
    cout << "  -Fazer com que seu servo cometa suicidio.\n\n";
    loading(3000);
    cout << "A feicao de Kirei estava extremamente seria quando dizia aquelas palavras, ele com certeza nao brincaria com algo tao serio.\n";
    loading(4500);
    cout << "Seu coracao esta disparado e voce nao sabe o que fazer.\n";
    loading(3500);
    cout << "Apenas pensar na possibilidade de obrigar a pessoa que passou por toda essa provacao contigo tirar sua propria vida...\n";
    loading(4500);
    cout << "Era algo pesado de mais, voces ja tinham passado por tanta coisa juntos, acabar dessa forma nao parecia justo.\n";
    loading(4500);
    cout << "Porem, o poder do Graal estava a um passo de distancia de ti, voce ja tinha pensado em milhares de possibilidades para usar o poder dele.\n";
    loading(4500);
    cout << "Conquistar o Santo Graal eh um objetivo unico, de imensuravel importancia, nao podia perder uma oportunidade como essa.\n\n";
    loading(4500);
    cout << "  -Entao, "<<nome<<", qual vai ser a sua escolha?\n\n";
    loading(3500);
    cout << "Apos pensar com cuidado, havia apenas uma escolha a ser feita, logo, voce responde: \n\n";
    loading(3500);
    cout << "\n\n======================= Escolha Sua Fala =======================\n\n";
    loading(3500);
    cout << " 1 - Mesmo depois que tudo que passei com meu servo, o Graal sempre foi o objetivo. Sei que ele entendera a minha escolha.\n";
    loading(4500);
    cout << " 2 - Jamais sacrificaria o aliado que travou todas essas batalhas ao meu lado, podem haver outras maneiras de completar o calice!\n\n";
    loading(4500);
    cout << "Faca sua escolha: ";
    cin >> escolha;
choice:
    
    switch(escolha){
        case 1:
            badending();
            return true;
            break;

        case 2:
           return false;
           
          break;
        default:
            cout << "\nOpcao incorreta, escolha uma opcao valida!\n";
            goto choice;
    }
}

void badending() {
    cout << "Kirei da um suspiro aliviado e responde: \n\n";
    loading(3500);
    cout << "  -Voce fez a decisao que qualquer outro mago teria tomado, sei que qualquer um compreenderia.\n";
    loading(4500);
    cout << "  -Agora, voce deve cumprir com sua palavra, mago\n\n";
    loading(3500);
    cout << "Seu peito estava pesado por causa da sua escolha, porem, era o unico caminho para atingir seu objetivo pelo calice.\n";
    loading(4500);
    cout << "Apos alguns instantes respirando fundo, que pareceram uma eternidade, voce convoca seu servo para dentro da igreja.\n";
    loading(4500);
    cout << "Voce o olha nos olhos e lembra de todas as batalhas que passaram juntos, porem, a decisao ja foi tomada. Logo, voce diz: \n\n";
    loading(4500);
    cout << "  -Voces servos nao sao chamdos de Espiritos Heroicos atoa, afinal, voce foi o heroi da nossa jornada.\n";
    loading(4500);
    cout << "  -Obrigado por tudo, eh uma pena que nossa historia se encerre assim...\n\n";
    loading(3500);
    cout << "Isso, voce aponta sua mao para seu servo e utiliza um selo de comando, obrigando que ele cometa suicidio.\n";
    loading(4500);
    cout << "Seu servo se assuta, e, antes que pudesse dizer qualquer coisa, ele utiliza sua propria arma para abrir um buraco no meio do seu peito.\n";
    loading(4500);
    cout << "Seu servo ia desaparecendo aos poucos, com uma expressao dessesperada, nao entendando o que estava acontecendo.\n";
    loading(4500);
    cout << "Toda vez que tentava dizer algo, a unica coisa qu saia de sua boca era sangue.\n\n";
    loading(3500);
    cout << "  -Perdao..._Foi a unica coisa que pode dizer naquela situacao.\n\n";
    loading(3500);
    cout << "Assim que seu servo morre e desaparece por completo, voce cai de joelhos no chao, exausto depois do que havia presenciado.\n";
    loading(4500);
    cout << "Porem, o clima de luto eh interrompido por uma alta risada que ecoava ela igreja.\n";
    loading(3500);
    cout << "Quando voce olha para cima, ve Kirei rindo, totalmenet alegre com a situacao.\n\n";
    loading(3500);
    cout << "  -VOCE EH UM TOLO, MAGO_Ele grita.\n\n";
    loading(3000);
    cout << "Nisso, uma poca de lama negra aparece no mesmo local que seu servo morreu.\n";
    loading(3500);
    cout << "Mesmo quase em panico, voce percebe que uma criatura comeca a sair dela. Bem, nao era uma criatura.\n";
    loading(4500);
    cout << "Voce consegue perceber que aquilo que estava saindo da lama negra era o seu servo, que havia acabado de morrer na sua frente.\n";
    loading(4500);
    cout << "Mas ele nao estava igual, todas as suas roupas agora eram pretas ou um roxo muito escuro.\n";
    loading(4500);
    cout << "Seu cabelo agora parecia totalmente apagado, e seus olhos estavam totalmente negros.\n";
    loading(3500);
    cout << "Nisso, Kirei para de rir e diz: \n\n";
    loading(3000);
    cout << "  -Tantos anos de batalhas, tantos anos de conflitos, apenas serviram para que o Graal guardasse total magoa e corrupcao gerada.\n";
    loading(4500);
    cout << "  -Esse Graal pelo que voce estava lutando tanto para conseguir, nao era o mesmo que originalmente foi criado.\n";
    loading(4500);
    cout << "  -Estava apenas aguardando a gota d'agua, o aperto no gatilho para que ele desmoronasse em puro caos.\n";
    loading(4500);
    cout << "  -E foi voce, voce foi aquele puxou o gatilho para a destruicao.\n";
    loading(3500);
    cout << "  -Agora, tera a consequencia de sua escolha.\n\n";
    loading(3000);
    cout << "Antes que pudesse responder de qualquer forma, a criatura, que uma vez foi seu servo e lutou ao seu lado, te ataca.\n";
    loading(4500);
    cout << "Voce nao consegue desviar pelo estado de choque que estava, e acaba tendo o perto perfurado pelo seu antigo aliado.\n";
    loading(4500);
    cout << "Em seus ultimos momentos de vida, antes de fechasse os olhos pela ultima vez, voce ve Kirei sorrindo.\n";
    loading(4500);
    cout << "Tu lembra de todas as lutas que teve que vencer, para que tudo acabasse dessa forma.\n";
    loading(3500);
    cout << "E assim, voce fecha os olhos pela ultima vez....\n";
    loading(3500);
    cout << "\n\n======================================== BAD ENDING ========================================\n\n";
    loading(3500);
    cout << "Nao mate o seu amiguinho.\n";
    loading(3500);
}

void batalha_kirei() {
    cout << "  -O que voce disse? -Pergunta Kirei, surpreso.\n\n";
    loading(3000);
    cout << "  -Como eu disse, nao vou sacrificar meu aliado assim, ele nao eh um obejto a ser descartado.\n\n";
    loading(4500);
    cout << "Kirei parecia profundamente confuso com tudo isso que voce estava dizendo.\n\n";
    loading(3500);
    cout << "  -Mas...voce vai desistir de conquistar todo o poder do calice apenas para poupar a vida de um servo?\n";
        loading(4500);
    cout << "  -E todos os outros servos que voce matou para chegar ate aqui? Ate mesmo mestres que voce matou!\n";
    loading(4500);
    cout << "  -A vida deles nao era importante?_Kirei estava quase gritando em cima de ti.\n\n";
    loading(3000);
    cout << "Voce logo e seguida reponde:\n\n";
    loading(3000);
    cout << "  -Sobre completar o calice, ja disse, encontrarei outra maneira sem ter que sacrificar meu servo.\n";
    loading(4500);
    cout << "  -Nao que a vida dele ou a minha seja mais importante do que de qualquer outra pessoa que acabamos matando.\n";
    loading(4500);
    cout << "  -Eu com certeza nao mereco um destino feliz depois que tudo que fiz.\n";
    loading(3000);
    cout << "  -Porem nao eh uma questao de valor da vida, e sim uma questao de decepcionar aquele o qual me depositou confianca.\n";
    loading(4500);
    cout << "  -Nao importa a situacao, nao trairia um aliado que lutou comigo todo esse tempo de uma forma tao covarde.\n\n";
    loading(3500);
    cout << "Kirei estava profundamente irritado com suas palavras, como se toda a situacao estivesse fora de controle.\n";
    loading(3500);
    cout << "Ele te encara por alguns segundos tem um olhar de pura decepcao.\n";
    loading(3000);
    cout << "Logo, ele respira fundo, procurando se acalmar.\n";
    loading(3000);
    cout << "Enquanto voce tentou entender tudo que esta acontecendo, Kirei saca uma faca.\n";
    loading(3500);
    cout << "Em menos de um piscar de olhos ele a arremessa em sua direcao.\n";
    loading(3000);
    cout << "Foi um movimento muito rapido, voce nao teve reacao a nao ser observar ela indo ao seu encontro.\n";
    loading(3500);
    cout << "Voce fecha com os olhos, ja esperando o impacto.\n";
    loading(3000);
    cout << "Porem, quando abre voce ve o seu servo na sua frente, que interceptou a faca pouco antes dela te acertar.\n\n";
    loading(3500);
    cout << "  -Vejo que o sentimento entre voces eh mutuo, mas nao sera isso que vai mante-los vivos aqui.\n\n";
    loading(3000);
    cout << "E, com isso, comeca a sua batalha contra o Kirei.\n";
    loading(3000);
}

void derrota_kirei(){
    cout << "Voce nao entende como Kirei poderia ser tao poderoso\n";
    loading(3000);
    cout << "Ele lutou de igual para igual contra voce e seu servo, estando sozinho.\n";
    loading(3000);
    cout << "Ele eh mesmo apenas o representante da igreja? Ele eh uma personificacao do calice? A igreja esta envolvida?\n";
    loading(4500);
    cout << "Pensamento assim nao saiam da sua cabeca, mesmo estando em completa exaustao.\n";
    loading(3000);
    cout << "Seu servo tambem estava muito ferido e exausto da batalha, mas nada se comparava ao Kirei.\n";
    loading(3500);
    cout << "Ele estava quase desacordado, caido no altar todo destruido por causa da batalha.\n";
    loading(3000);
    cout << "Seu rosto estava todo ensanguentado, e voce tinha certeza que ao menos seus dois bracos estavam quebrados.\n\n";
    loading(4500);
    cout << "  -Nao...nao pode acabar assim._Kirei murmura em meio a algumas leves risadas.\n";
    loading(3000);
    cout << "  -Era para voce sacrifica-lo, tinha que fazer apenas isso. Por que nao o fez?!\n\n";
    loading(3500);
    cout << "Voce simplesmente nao conseguia mais ouvir uma palavra sequer dequele homem.\n";
    loading(3500);
    cout << "Entao aponta sua arma para ele, mas antes que pudesse atirar, seu servo foi mais rapido e finalizou a batalha.\n";
    loading(4500);
    cout << "Logo apos isso, voce percebe que algo estranho se formava atras do altar quabrado.\n";
    loading(3500);
    cout << "Um grande calice dourado apareceu na sua frente, sendo iluminado pela luz da lua que entrava pelas vidracas.\n";
    loading(4500);
    cout << "Apos uma troca de olhares rapida com o seu servo, voce caminha lentamente em direcao ao calice.\n";
    loading(3500);
    cout << "Quanto mais perto voce chegava dele, mais podia sentir o poder magico que ele emanava.\n";
    loading(3500);
    cout << "E, quando voce finalmente chegou, pegou-o com suas proprias maos.\n";
    loading(3500);
    cout << "Porem, algo estava errado.\n";
    loading(3000);
    cout << "Assim que voce o tocou, ele comecou a transbordar uma lama escura e grossa.\n";
    loading(3500);
    cout << "O poder magico intenso que antes havia nele foi transformado para algo sujo e assustador.\n";
    loading(3500);
    cout << "O pior havia acontecido.\n\n";
    loading(3000);
    cout << "O Santo Graal ja estava corrompido";
    loading(1500);
    cout << ".";
    loading(1500);
    cout << ".";
    loading(1500);
    cout << ".\n\n";
    loading(1500);
}
void creditos() {
    cout << " ======== DESENVOLVEDORES ======== \n\n";
    cout << " ANA PAULA BESSA MEDEIROS \n";
    cout << " MATEUS XIMENES DE OLIVEIRA \n";
    cout << " MATHEUS FERRAZ CAPUCHO \n";
    cout << " PEDRO HENRIQUE BRIGAGAO DE AVILA \n";
    cout << " RENATO MASTEGUIM NETO \n";
    loading(3000);
}